name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v7

      - name: Konfiguracja Pythona
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Instalacja zależności
        run: python -m pip install -r requirements.txt

      - name: Uruchomienie testów
        run: python -m pytest -v
